name: social_media_logins
description: A new Flutter package project.
version: 0.0.1
homepage: asdasd

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # PACKAGES
  http: ^0.13.4
  flutter_login_facebook:
  google_sign_in:
  sign_in_with_apple:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
